# Generated by Django 2.0.7 on 2019-06-01 13:02

import datapeace.core_lib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.CharField(default=datapeace.core_lib.generate_unique_object_id, max_length=24, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('web', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'A. User Data',
                'ordering': ['first_name', 'last_name', 'age'],
            },
        ),
    ]
